topic : inbound
spring:
  cloud:
    stream:
      defaultBinder: rabbit
      rabbit:
        binder:
          nodes: localhost:7777  
  rabbitmq:
    addresses: localhost:7777
    host: localhost
    port: 7777
    username: scdf
    password: scdf
  security:
    user:
      name: scdf
      password: scdf     
server:
  port: 19999

  